### ISSUE TITLE
Effect of `-L` and `-R` is unclear

### ISSUE THREAD

**Issue by ISSOtm** [bbbbbr/png2hicolorgb#1]
- [ ] The help text mentions "left" and "right" attributes, but it seems unclear as to what this is referring to.

- [ ] That help text also mentions "fast" and "optimal", but those are ambiguous:
    - Does "fast" refer to processing speed, or how much CPU will be used on the GB side?
    - Does "optimal" refer to how close the GB image will be to the source image?

- [ ] Additionally, being able to specify the textual versions would be more ergonomic than being forced to pass "magic" numbers (`-L 0` vs. `-L Adaptive-fast`; precedent: `rgbfix -m $19` vs. `rgbfix -m MBC5`)

**Comment by bbbbbr** [comment]
Good points. I can try to clarify some of these details in the attribute table help text.

- Slower/faster is conversion speed on the PC. If my understanding is right, in adaptive mode it's the number of combinations it tries for finding the best use of CGB palette/attributes on 8x2 pixel tiles within an 80x2 pixel Left or Right screen region. 
- Correct, optimal refers to how closely the conversion is able to approximate the source image1.

**Comment by ISSOtm** [comment]
Considering the amount of work this tool does compared to modern processing power, it seems like the defaults can be shifted to more intensive settings.

**Comment by bbbbbr** [comment]
- Bumping up to Adaptive-2 (`-L=1, -R=1`) seems reasonable
- Maybe also an easy preset for max quality `--best` (`--type=3, -L=2, -R=2`)
- Could add a middle-ground adaptive setting (the current options 6, 10, 80 seem to lack a mid-range)
- Until I removed it the default used to be the Jeff F. method which was about 2-4x faster (but lower output quality)

I'd like to continue being mindful of low spec systems though (my dev system included) where higher settings are tangibly slow.

For example, to clean build the GBDK example (most time spent in the converter app):
- `--type=1 -L=1 -R=1` : 9 seconds
- `--type=3 -L=1 -R=1` : 31 seconds
- `--type=1 -L=2 -R=2` : 59 seconds
- `--type=3 -L=2 -R=2` : 232 seconds

**Comment by ISSOtm** [comment]
If not changing the settings, noting those presets you've found in e.g. the README should be beneficial. (I must admit I haven't paid much attention to measuring the build time, it just seemed "fast enough" to me 😅)

**Comment by bbbbbr** [comment]
Improvements for these items in commit: 859f1d2adea2eb
