### ISSUE TITLE
Supporting other image formats

### ISSUE THREAD

**Issue by ISSOtm** [bbbbbr/png2hicolorgb#2]
I can suggest using [libplum](https://github.com/aaaaaa123456789/libplum) to load images instead of LodePNG. More image formats (especially BMP and GIF, which are still seeing wide use) are supported, still under a uniform interface that shouldn't increase complexity on our side.

The license (Unlicense) is compatible, and the library is designed to be importable in-source.

**Comment by bbbbbr** [comment]
Closing this for now, but if there are additional requests to support other image formats than it can be revisited.

**Comment by bbbbbr** [comment]
Fixing close status

**Comment by bbbbbr** [comment]
Fixing close status
