### ISSUE TITLE
Shorten help text

### ISSUE THREAD

**Issue by ISSOtm** [bbbbbr/png2hicolorgb#4]
The current help text is really long, especially for what's displayed on "usage failure". For that use case, the actual usage info is diluted by the version / credits info.

A common pattern is to omit the non-essential info outside of `--help` and/or `-h` (and to have the latter be more terse than the former).

For a precedent / similar discussion: https://github.com/gbdev/rgbds/pull/455#discussion_r355149323

**Comment by bbbbbr** [comment]
Good idea :+1:

**Comment by bbbbbr** [comment]
Improvement for this in commit: 859f1d2adea2eb
