### ISSUE TITLE
Use 15th bit on last pushed color to determine the end of the rendered image

### ISSUE THREAD

**Issue by coffeevalenbat** [bbbbbr/png2hicolorgb#6]
I'm currently using this tool alongside a very modified version of the original display code, since I begun working with the original tool a few months before this came around. Recently I reworked the code (and my middleman python tool) to use the 15th bit of the last pushed color to determine the end of the render loop, since I'm rendering images smaller than 144 in height. This check is only 2 cycles and bytes compared to checking rLY (3 cycles to fetch rLY, 2 to compare it), plus it gives more flexibility than hardcoding the line end of the render. Perhaps an option for this could be added in the future? since the last bit isn't used either way.

From my middle-man python tool:
![image](https://github.com/bbbbbr/png2hicolorgb/assets/34352018/f58551d6-85b9-4172-bac1-5adb0b27bac7)
And a bit of my modified render code (not interrupt based like the modern RGBDS example):
![image](https://github.com/bbbbbr/png2hicolorgb/assets/34352018/cd26e1f2-eee6-433d-a9fa-41271a8adae4)

**Comment by bbbbbr** [comment]
Oops, forgot to submit my comment here before rebooting. :)

Yes, good idea. I can make it an option.

The current C example supports input images that are both shorter and taller (scrolling) than the screen height, so I'll think about whether to update those to use it or not.

**Comment by bbbbbr** [comment]
If you have some time, it would be helpful if you could test this github build with the new `--palendbit` flag:
https://github.com/bbbbbr/png2hicolorgb/actions/runs/7839784466
